{{- if .Values.pvc.create -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "helm-chart-java-pipeline.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources }}
{{- end -}}
