{{- if .Values.secrets.quay.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
stringData:
  config.json: |
    {
      "auths": {
        "quay.io": {
          "auth": ""
        }
      }
    }
{{- end -}}
