{{- if .Values.secrets.git.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.git.name }}
  annotations:
    tekton.dev/git-0: {{ .Values.git.host }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: >-

  known_hosts: >-

{{- end -}}
