apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .Values.pipelineTasks.mvnBuild.name }}
spec:
  workspaces:
    - name: source
  steps:
    - name: build-sources
      image: {{ .Values.pipelineTasks.mvnBuild.image }}:{{ .Values.pipelineTasks.mvnBuild.tag }}
      workingDir: "$(workspaces.source.path)"
      command:
        - /usr/bin/mvn
      args:
        - clean
        - package
