{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-chart-java-pipeline.serviceAccountName" . }}
  labels:
    {{- include "helm-chart-java-pipeline.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ .Values.secrets.git.name }}
{{- end }}
